import { gqlRequest } from '../client';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ProductImage {
    url: string;
    alt?: string;
}

export interface ProductCategory {
    id: string;
    name: string;
    slug: string;
    image?: {
        big1x: string | null;
        big2x: string | null;
    } | null;
    children?: ProductCategory[];
}

export interface Product {
    id: string;
    slug?: string;
    categoryId?: number;
    name: string;
    cost: number;
    oldCost?: number;
    unit: string;
    multiplier?: number;
    is_new?: boolean;
    available?: boolean;
    image?: {
        url: {
            grid2x: string;
            grid1x?: string;
            main2x?: string;
            main1x?: string;
            big?: string;
        };
    } | null;
    specifications?: {
        name: string;
        values: string[];
    }[];
}

export interface ProductsFilter {
    categoryId?: number | null;
    limit?: number | null;
    page?: number | null;
}

export interface ProductsResponse {
    data: Product[];
    per_page: number;
    current_page: number;
    has_more_pages: boolean;
}

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

const PRODUCTS_QUERY = /* GraphQL */ `
    query Products($categoryId: Int, $limit: Int, $page: Int) {
        products(categoryId: $categoryId, limit: $limit, page: $page) {
            per_page
            current_page
            has_more_pages
            data {
                id
                slug
                categoryId
                name
                cost
                oldCost
                unit
                multiplier
                is_new
                available
                image {
                    url {
                        grid2x
                        grid1x
                        main2x
                        main1x
                        big
                    }
                }
                specifications {
                    name
                    values
                }
            }
        }
    }
`;

const PRODUCT_BY_ID_QUERY = /* GraphQL */ `
    query Product($id: Int!) {
        product(id: $id) {
            id
            slug
            categoryId
            name
            cost
            oldCost
            unit
            multiplier
            is_new
            available
            text
            image_alt
            image_title
            hasCostVariants
            hasGift
            giftText
            rating
            specifications {
                name
                values
            }
            image {
                url {
                    grid2x
                    grid1x
                    main2x
                    main1x
                    big
                }
            }
        }
    }
`;

const CATEGORIES_QUERY = /* GraphQL */ `
    query Categories {
        categories {
            id
            name
            slug
        }
    }
`;

const VIEWED_PRODUCTS_QUERY = /* GraphQL */ `
    query ViewedProducts($limit: Int) {
        products(viewed: true, limit: $limit) {
            data {
                id
                name
                cost
                oldCost
                unit
                multiplier
                is_new
                image {
                    url {
                        grid2x
                    }
                }
                specifications {
                    name
                    values
                }
            }
        }
    }
`;

// ---------------------------------------------------------------------------
// API functions
// ---------------------------------------------------------------------------

export async function getProductsApi(filter?: ProductsFilter, lang?: string): Promise<ProductsResponse> {
    const data = await gqlRequest<{ products: ProductsResponse }>(
        PRODUCTS_QUERY,
        {
            categoryId: filter?.categoryId ?? null,
            limit: filter?.limit ?? null,
            page: filter?.page ?? null
        },
        { next: { revalidate: 60 }, lang },
    );
    return data.products;
}

export async function getProductByIdApi(id: number | string, lang?: string): Promise<Product> {
    const data = await gqlRequest<{ product: Product }>(
        PRODUCT_BY_ID_QUERY,
        { id: parseInt(String(id)) },
        { next: { revalidate: 60 }, lang },
    );
    return data.product;
}

/**
 * Resolves a product slug to its numeric id.
 * Scans products paginated (100/page, max 2000 products) with 1-hour cache.
 * Used only when the page is not pre-generated by generateStaticParams.
 */
export async function findProductIdBySlug(
    slug: string,
    lang?: string,
): Promise<string | null> {
    const limit = 100;
    const maxPages = 20;

    // Minimal fields query — just id and slug for fast resolution
    const SLUG_SCAN_QUERY = /* GraphQL */ `
        query ProductsScan($limit: Int, $page: Int) {
            products(limit: $limit, page: $page) {
                has_more_pages
                data { id slug }
            }
        }
    `;

    for (let page = 1; page <= maxPages; page++) {
        const data = await gqlRequest<{
            products: { has_more_pages: boolean; data: Array<{ id: string; slug?: string }> };
        }>(
            SLUG_SCAN_QUERY,
            { limit, page },
            { next: { revalidate: 3600 }, lang },
        );

        const found = data.products.data.find((p) => p.slug === slug);
        if (found) return found.id;
        if (!data.products.has_more_pages) return null;
    }

    return null;
}

export async function getCategoriesApi(lang?: string): Promise<ProductCategory[]> {
    const data = await gqlRequest<{ categories: ProductCategory[] }>(
        CATEGORIES_QUERY,
        undefined,
        { next: { revalidate: 3600 }, lang },
    );
    return data.categories;
}

const CATEGORY_TREE_QUERY = /* GraphQL */ `
    query CategoriesTree {
        categories {
            id
            name
            slug
            image {
                big1x
                big2x
            }
            children {
                id
                name
                slug
                image {
                    big1x
                    big2x
                }
                children {
                    id
                    name
                    slug
                }
            }
        }
    }
`;

export async function getCatalogTreeApi(lang?: string): Promise<ProductCategory[]> {
    const data = await gqlRequest<{ categories: ProductCategory[] }>(
        CATEGORY_TREE_QUERY,
        undefined,
        { next: { revalidate: 3600 }, lang },
    );
    return data.categories;
}

export async function getViewedProductsApi(limit: number = 10, lang?: string, token?: string): Promise<Product[]> {
    const data = await gqlRequest<{ products: { data: Product[] } }>(
        VIEWED_PRODUCTS_QUERY,
        { limit },
        { next: { revalidate: 60 }, lang, token },
    );
    return data.products.data;
}
